name: Connection Test to Azure
on: push
jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
      - name: Check Azure Connection
        uses: azure/cli@v1
        with:
          inlineScript: |
            az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
            az account show
        
  
