on: [push]

name: AzureARMDeploy

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{AZURE_CREDENTIALS}'
          enable-AzPSSession: true
      - name: List installed modules
        run: |
          set -e
          module list

      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          inlineScript: |
            get-azcontext
            Get-AzResourceGroup
          azPSVersion: "latest"
