
  name: Azure ARM
  on: push
  jobs:
    build-and-deploy:
      runs-on: self-hosted
      steps:

        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          enable-AzPSSession: true
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          azPSVersion: "7.5.0"
         
      - name: Create ResourceGroup
        uses: azure/CLI@v1
        with:
          inlineScript: |
            call New-AzResourceGroup -Name ${{ secrets.AZURE_RG }} -Location "West Europe"
      - name: Set PowerShell execution policy
        uses: azure/CLI@v1
        with:
          inlineScript: |
            Set-ExecutionPolicy Unrestricted
            
      - name: Install Az.Resources PowerShell Module
        uses: azure/CLI@v1
        with:
          inlineScript: |
            Get-Module -Name Az.Resources -AllowClobber -Scope CurrentUser

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./azuredeploy.json
          parameters: storageAccountType=Standard_LRS

        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}
